version: 2

snapshots:
  - name: players_snapshot
    description: a snapshot of the players table to track changes over time player_position, player_team_id, player_current_cost, player_total_points
    relation: ref('players_cleansed')
    config:
      unique_key: player_id
      strategy: check
      check_cols: ['player_position', 'player_team_id', 'player_current_cost', 'player_total_points']
      hard_deletes: 'new_record'
    columns:
      - name: player_id
        description: Player ID
      - name: player_first_name
        description: First name of the player
      - name: player_second_name
        description: Second name of the player
      - name: player_name
        description: Full name of the player
      - name: player_position
        description: Position of the player that could change over time
      - name: player_team_id 
        description: Team ID of the player that could change over time
      - name: player_current_cost
        description: Current cost of the player that could change over time
      - name: player_total_points
        description: Total points of the player that could change over time
      - name: ingestion_time
        description: Time of ingestion
      - name: dbt_scd_id
        description: Id for the dbt scd (internal to dbt)
      - name: dbt_updated_at 
        description: Timestamp of the update
      - name: dbt_valid_from
        description: Timestamp of the start of the validity of the record
      - name: dbt_valid_to
        description: if present Timestamp of the end of the validity of the record
      - name: dbt_is_deleted
        description: Boolean to indicate if the record is deleted 

  - name: teams_snapshot
    description: a snapshot of the teams table to track strengthes changes over time
    relation: ref('teams_cleansed')
    config:
      unique_key: team_id
      strategy: check
      check_cols: ['team_strength', 'strength_overall_home', 'strength_overall_away', 'strength_attack_home', 'strength_attack_away', 'strength_defence_home', 'strength_defence_away']
      hard_deletes: 'new_record'
    columns:
    - name: team_id
      description: Team ID
    - name: team_name
      description: Name of the team
    - name: team_short_name
      description: Short name of the team
    - name: team_strength
      description: Strength of the team that could change over time
    - name: strength_overall_home
      description: Strength of the team at home that could change over time
    - name: strength_overall_away
      description: Strength of the team away that could change over time
    - name: strength_attack_home
      description: Strength of the team attack at home that could change over time
    - name: strength_attack_away
      description: Strength of the team attack away that could change over time
    - name: strength_defence_home
      description: Strength of the team defence at home that could change over time
    - name: strength_defence_away
      description: Strength of the team defence away that could change over time
    - name: ingestion_time
      description: Time of ingestion
    - name: dbt_scd_id
      description: Id for the dbt scd (internal to dbt)
    - name: dbt_updated_at
      description: Timestamp of the record's update
    - name: dbt_valid_from
      description: Timestamp of the start of the validity of the record
    - name: dbt_valid_to
      description: if present Timestamp of the end of the validity of the record
    - name: dbt_is_deleted
      description: Boolean to indicate if the record is deleted