fantasy_premier_league:                 # Your profile name
  outputs:                # Defines environments
    duck:                  # Development environment
      type: duckdb        # Database type
      # path: coding/personal-projects/fantasy-premier-league-etl/fpl.db        # Path to your DuckDB file
      path: ../fpl.db 
      threads: 1          # Number of threads for queries

    bq:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_GCP_PROJECT') }}" #fantasy-premier-league-447918
      dataset: "{{ env_var('DBT_TARGET_DATASET') }}" #fantasy_premier_league # You can also use "schema" here
      threads: 1 # Must be a value of 1 or greater 

  target: bq             # Default environment